services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8000"
    env_file:
      - .env
    environment:
      - COURSES_SERVICE_URL=http://courses-service:8000
      - AI_COURSE_GEN_SERVICE_URL=http://ai-course-gen-service:8000
      - PRONUNCIATION_FEEDBACK_SERVICE_URL=http://pronunciation-feedback:8000
      - USER_PROFILE_SERVICE_URL=http://user-profile-service:8000
    depends_on:
      - courses-service
      - ai-course-gen-service
      - pronunciation-feedback
      - user-profile-service

  courses-service:
    build: ./services/courses-service
    ports:
      - "8081:8000"
    env_file:
      - .env

  ai-course-gen-service:
    build: ./services/ai-course-gen-service
    ports:
      - "8082:8000"
    env_file:
      - .env
  
  user-profile-service:
    build: ./services/user-profile-service
    ports:
      - "8083:8000"
    env_file: 
      - .env
  pronunciation-feedback:
    build: ./services/pronunciation-feedback
    ports:
      - "8084:8000"
    env_file:
      - .env