-- Shared turn/score state for active group-session rounds.
-- One row per (lobby_kind, lobby_id), updated by group-service.

create table if not exists public.lobby_turn_states (
  id bigint generated by default as identity primary key,
  lobby_kind text not null check (lobby_kind in ('private', 'public')),
  lobby_id bigint not null,
  scores_by_user jsonb not null default '{}'::jsonb,
  next_round_votes jsonb not null default '[]'::jsonb,
  event_seq integer not null default 0,
  latest_scored_user_id uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lobby_kind, lobby_id)
);

create index if not exists idx_lobby_turn_states_kind_id
  on public.lobby_turn_states (lobby_kind, lobby_id);

create or replace function public.touch_lobby_turn_states_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_lobby_turn_states_updated_at on public.lobby_turn_states;
create trigger trg_touch_lobby_turn_states_updated_at
before update on public.lobby_turn_states
for each row execute procedure public.touch_lobby_turn_states_updated_at();

create or replace function public.cleanup_lobby_turn_state_when_empty()
returns trigger
language plpgsql
as $$
begin
  if tg_table_name = 'private_lobbies' then
    if not exists (select 1 from public.private_lobbies where lobby_id = old.lobby_id) then
      delete from public.lobby_turn_states
      where lobby_kind = 'private' and lobby_id = old.lobby_id;
    end if;
  elsif tg_table_name = 'public_lobbies' then
    if not exists (select 1 from public.public_lobbies where lobby_id = old.lobby_id) then
      delete from public.lobby_turn_states
      where lobby_kind = 'public' and lobby_id = old.lobby_id;
    end if;
  end if;
  return null;
end;
$$;

drop trigger if exists trg_cleanup_turn_state_private on public.private_lobbies;
create trigger trg_cleanup_turn_state_private
after delete on public.private_lobbies
for each row execute procedure public.cleanup_lobby_turn_state_when_empty();

drop trigger if exists trg_cleanup_turn_state_public on public.public_lobbies;
create trigger trg_cleanup_turn_state_public
after delete on public.public_lobbies
for each row execute procedure public.cleanup_lobby_turn_state_when_empty();
