"""
course_schema.py

Pydantic schemas for request/response shapes.

Purpose:
- Define the "API contract" for courses endpoints.
- Validate inputs and structure outputs consistently.

Rule of thumb:
- PrivateLobbyCreate = What the client sends to create a private lobby.
- JoinPrivateLobby   = What the client needs to join a user to a lobby.
- GetPrivateLobby    = What the api returns to the client.
"""

from datetime import datetime

from pydantic import BaseModel, Field

class PrivateLobbyCreate(BaseModel):
    """
    Request shape for creating a private lobby.

    Fields:
    - username: The name of the user creating the lobby. Required to set the host and create the first member.
    """

    username: str
    user_id: str

class PrivateLobbyJoin(BaseModel):
    """
    Request shape for joining a private lobby.

    Fields:
    - user_id: The ID of the user joining the lobby.
    - lobby_id: The ID of the lobby to join.
    - username: The name of the user joining the lobby.
    """
    lobby_id: int
    username: str
    user_id: str

class PrivateLobbyMemberOut(BaseModel):
    """
    Response shape for a member of a private lobby  returned from the DB.

    Fields match the columns we select from Supabase.
    Supabase returns JSON, and Pydantic converts types:
    - id/user_id -> UUID
    - created_at -> datetime
    """

    id: str
    lobby_id: int
    username: str
    user_id: str
    host: bool
    session_start: bool
    joined_at: datetime


class PrivateLobbyDeleteOut(BaseModel):
    deleted: bool


class LobbyTurnParticipantOut(BaseModel):
    user_id: str
    username: str
    turn_order: int
    score: float | None = None


class LobbyTurnStateOut(BaseModel):
    lobby_id: int
    lobby_kind: str
    round_number: int = 0
    current_turn_index: int
    participants: list[LobbyTurnParticipantOut]
    round_complete: bool
    event_seq: int
    latest_scored_user_id: str | None = None
    next_round_votes: list[str] = Field(default_factory=list)
    next_round_vote_count: int = 0


class LobbyTurnScoreIn(BaseModel):
    score: float = Field(ge=0, le=100)


class LobbyNextRoundVoteOut(BaseModel):
    """
    Kept as a distinct response model option if we later want to return something
    other than the full LobbyTurnStateOut.
    """

    state: LobbyTurnStateOut


class LobbyItemOut(BaseModel):
    """
    A single pronunciation practice item stored in lobby_items.

    Fields match the columns selected from Supabase.
    """
    position: int
    text: str
    ipa: str | None = None
    hint: str | None = None


class SetLobbyItemsReq(BaseModel):
    """
    Request body for storing a batch of items for a lobby session.

    Fields:
    - items: Ordered list of practice items generated by the AI service.
    """
    items: list[LobbyItemOut] = Field(default_factory=list)
