from typing import Protocol
from uuid import UUID

from app.schemas.follow_schema import SocialUserOut


class FollowRepo(Protocol):
    async def list_followers(self, user_id: UUID) -> list[SocialUserOut]: ...
    async def list_following(self, user_id: UUID) -> list[SocialUserOut]: ...
    async def get_counts(self, user_id: UUID) -> tuple[int, int]: ...
    async def search_profiles(self, user_id: UUID, q: str, limit: int) -> list[SocialUserOut]: ...
    async def follow(self, follower_id: UUID, followee_id: UUID) -> None: ...
    async def unfollow(self, follower_id: UUID, followee_id: UUID) -> None: ...
    async def block(self, blocker_id: UUID, blocked_id: UUID) -> None: ...
    async def unblock(self, blocker_id: UUID, blocked_id: UUID) -> None: ...
    async def list_blocked_ids(self, user_id: UUID) -> list[str]: ...
    async def delete_account(self, user_id: UUID) -> None: ...