"""
generate_schema.py

AI Course Generation Schemas (Data Models)

Purpose:
- Define request and response shapes for AI-generated course content.
- Validate incoming prompts and structure AI-generated output.
- Serve as the contract between the Gateway and the AI service.

Architecture:
Gateway → AI Course Gen Service (this service)

Schema Types:
- GenerateCourseReq → input from Gateway (user prompt)
- GenerateCourseRes → structured AI output (course + lessons + items + image)

Notes:
- These schemas are NOT direct database models.
- They represent intermediate AI-generated content before persistence.
- The Gateway or another service (e.g., courses-service) is responsible
  for storing this data.
"""

from pydantic import BaseModel, Field
from typing import List, Optional


class LessonItem(BaseModel):
    """
    Represents a single pronunciation prompt inside a lesson.

    Fields:
    - text: The phrase or sentence the user should practice.
    - ipa: Optional phonetic transcription (can be generated or omitted).
    - hint: Optional helper text for pronunciation guidance.
    """
    text: str
    ipa: Optional[str] = None
    hint: Optional[str] = None


class Lesson(BaseModel):
    """
    Represents a lesson generated by the AI.

    Fields:
    - title: Name of the lesson (e.g., "Ordering Food").
    - items: Ordered list of lesson items (prompts).

    Notes:
    - items defaults to an empty list but is expected to be populated by the AI.
    """
    title: str
    items: List[LessonItem] = Field(default_factory=list)


class GenerateCourseReq(BaseModel):
    """
    Request schema for generating a course.

    Fields:
    - prompt: Free-text input describing what the user wants to learn.

    Validation:
    - Required field
    - Minimum length ensures non-empty input
    - Maximum length prevents excessively large prompts
    """
    prompt: str = Field(..., min_length=1, max_length=5000)


class GenerateCourseRes(BaseModel):
    """
    Response schema for AI-generated course content.

    Fields:
    - title: Generated course title
    - image_url: Selected course cover image URL
    - lessons: List of generated lessons, each with items

    Notes:
    - This is structured output from the AI/image-selection layer, not yet persisted.
    - The Gateway or courses-service may take this response and:
        1. Create a course
        2. Store image_url
        3. Insert lessons and lesson items
    """
    title: str
    image_url: Optional[str] = None
    lessons: List[Lesson] = Field(default_factory=list)


class GenerateSessionItemsReq(BaseModel):
    """
    Request schema for generating a flat list of session items for group play.

    Fields:
    - topic: A short topic string that guides the LLM (e.g. "Daily routines").
    """
    topic: str = Field(..., min_length=1, max_length=200)


class GenerateSessionItemsRes(BaseModel):
    """
    Response schema for AI-generated group session items.

    Returns a flat list of 20 pronunciation prompts — no course or lesson nesting.
    Each item has the same shape as a course LessonItem.
    """
    items: List[LessonItem] = Field(default_factory=list)